apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
spec:
  type: LoadBalancer
  selector:
    app: webgoat
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

